### ISSUE TITLE
Replacing all calls with asynchronous:

### ISSUE THREAD

**Issue by milovidov983** [hflabs/dadata-csharp#10]
Good day.
I noticed that you use all calls to the network in a synchronous way, I don’t understand why?

I migrate your library to .Net Standart and fixed all the calls:
https://github.com/hflabs/dadata-csharp/pull/12

**Comment by nalgeon** [comment]
Реализовано в версии [20.7.3](https://www.nuget.org/packages/Dadata/20.7.3).
