### ISSUE TITLE
Нужна версия под .net core

### ISSUE THREAD

**Issue by navff** [hflabs/dadata-csharp#14]
Нужна версия под .net core. Сделаете? Когда?

**Comment by milovidov983** [comment]
> Нужна версия под .net core. Сделаете? Когда?

Я переписал на netstandard и создал PR, но насколько я понимаю, разработчики не часто следят за данным репозиторием так как PR открыт 12 декабря 2019 и ответов по прежнему нет https://github.com/hflabs/dadata-csharp/pull/12.

Если хотите можете взять мою версию:  https://github.com/milovidov983/dadata-csharp

**Comment by a-a-k** [comment]
https://github.com/Xambey/DaData.ApiClient

**Comment by nalgeon** [comment]
Свежая версия сделана под .net standard 2.0: https://www.nuget.org/packages/Dadata/20.7.0
