### ISSUE TITLE
SuggestClient не отдаёт данные

### ISSUE THREAD

**Issue by amstr1k** [hflabs/dadata-csharp#15]
нп — населённый пункт;
кп — курортный посёлок;
к. — кишлак;

при вызове клиента возвращается пустой массив

**Comment by milovidov983** [comment]
> нп — населённый пункт;
> кп — курортный посёлок;
> к. — кишлак;
> 
> при вызове клиента возвращается пустой массив

Приведите пожалуйста полностью ваш код, что бы можно было воспроизвести ошибку.

**Comment by amstr1k** [comment]
> Приведите пожалуйста полностью ваш код, что бы можно было воспроизвести ошибку.
а дело собственно не в коде и не в клиенте. Вызовите API с данными которые выше, в ответ получите пустой массив.

**Comment by nalgeon** [comment]
Не имеет отношения к .NET-клиенту. Если что-то не так в работе API — напишите, пожалуйста, [в поддержку](https://dadata.ru/support) конкретный пример (что на входе, что на выходе, что ожидаете).
