### ISSUE TITLE
Поддержка HttpClientFactory

### ISSUE THREAD

**Issue by rus-art** [hflabs/dadata-csharp#17]
Добрый день! Чтобы использовать клиенты вместе с [HttpClientFactory в AspNet Core](https://docs.microsoft.com/ru-ru/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1), необходимы конструкторы, принимающие HttpClient в качестве аргументов. Сейчас создание HttpClient лежит на ответственности клиентов. Предлагаю добавить такие конструкторы.

**Comment by nalgeon** [comment]
Спасибо! Вошло в релиз [20.8.1](https://github.com/hflabs/dadata-csharp/releases/tag/20.8.1)

**Comment by VitalyV** [comment]
@rus-art @nalgeon Подскажите, как вы это используете в коде? Какие параметры указываете при `AddHttpClient` и как создаёте клиента в методе. Спасибо
