### ISSUE TITLE
Visual Studio error

### ISSUE THREAD

**Issue by petroglif-tech** [hflabs/dadata-csharp#24]
Во время работы приложения вылетает ошибка:
Не удалось загрузить тип "Dadata.SuggestClient" из сборки "Dadata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"

код:
var token = "MyToken";
var api = new SuggestClient(token);
var result = api.FindParty("7707083893");

версия 20.10.0

**Comment by nalgeon** [comment]
Еще актуально?

**Comment by daiser** [comment]
Да, актуально.
21.9.0
.NET Framework 4.8
