### ISSUE TITLE
Incorrect Usage of HttpClient

### ISSUE THREAD

**Issue by force-net** [hflabs/dadata-csharp#29]
In ClientBaseAsync you by default use construction `new HttpClient()` - it is incorrect usage of this class an can cause resource leak, if user will create descendants of this class.

You can check this in [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0)

> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors.

https://github.com/hflabs/dadata-csharp/blob/47583a907082bc88460182509ae663aab5f2bb9f/Dadata/ClientBaseAsync.cs#L23

**Comment by nalgeon** [comment]
I believe that for simple use cases it is perfectly fine to create an instance of `HttpClient` inside the Dadata client and use it. For more complex scenarios, one can pass an existing `HttpClient` instance into the constructor.
