### ISSUE TITLE
Отсутствует компонента земельного участка в объекте адреса

### ISSUE THREAD

**Issue by greedox** [hflabs/dadata-csharp#38]
В объекте https://github.com/hflabs/dadata-csharp/blob/master/Dadata/Model/Address.cs отстутствуют параметры:
<html>
<body>

Название | Описание
-- | --
data.stead_fias_id | ФИАС-код земельного участка
data.stead_kladr_id | КЛАДР-код земельного участка
data.stead_type | = «уч»
data.stead_type_full | = «участок»
data.stead | номер земельного участка

</body>
</html>

В методе https://dadata.ru/api/suggest/address/ они присутствуют.

**Comment by nalgeon** [comment]
Спасибо! Вошло в [23.5.0](https://github.com/hflabs/dadata-csharp/releases/tag/23.5.0)
