### ISSUE TITLE
Тесты попадают в nuget-пакет

### ISSUE THREAD

**Issue by impworks** [hflabs/dadata-csharp#7]
В nuget-пакете доступен класс `CleanClientTest`, которого там быть не должно. Кроме того, из-за этого у пакета пакет требует `NUnit` в качестве зависимости.

**Comment by nalgeon** [comment]
У этого репозитория вообще нет nuget-пакета. Есть два форка с пакетами, оба сделаны сторонними разработчиками: <https://www.nuget.org/packages?q=dadata>

**Comment by mryabets** [comment]
Вынес тесты в отдельный проект в своём форке (библиотека `DaData.Client.Clean`), если всё ещё интересует.

**Comment by nalgeon** [comment]
Anyway, теперь тесты вынесены в отдельный проект, так что в основную сборку не попадают.
